@startuml container diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5

!include FONTAWESOME/users.puml

title Container Diagram v0.2

Person(user, "User")
Person(auditor, "Auditor")

Container_Boundary(system_boundary, "Ledger Hub"){
  Container(userUI,"User UI","ReactJS - Microservice", "Single Page App")
  Container(auditorUI, "Admin UI", "ReactJS - Microservice", "Single Page App")
  Container(auth, "Authentication Service","Golang Fiber - Microservice","Handle\nlogin, register, forget password, and logout")
  Container(account, "Account Service","Golang Fiber - Microservice")
  Container(ledger, "Ledger Service","Golang Fiber - Microservice")
  Container(deposit, "Deposit Service","NestJS - Microservice")
  Container(withdraw, "Withdraw Service","ElysiaJS - Microservice")
  Container(notification, "Notification Service","Java Spring Boot - Microservice")
  Container(reconciliation, "Reconciliation Service","NestJS - Microservice","Periodically compare balance in system and blockchain")
  ContainerDb(db, "Database","PostgreSQL","Store all microservices data separated by postgres schema" )
  Container(kafka,"Distributed Event Streaming Platform", "Apache Kafka","Handle event-based communication between microservices")
}

ContainerDb_Ext(blockchain, "Kub Chain", "Bitkub's blockchain","Blockchain")
Container_Ext(email, "SendGrid", "Software as a Service","Email API provider")
Container_Ext(r2, "Cloudflare R2","Storage as a Service", "Object Storage for file types data ex. user profile, reconcile report, and back-up")

Rel_U(user, userUI, "Uses")
Rel_U(userUI, auth, "Make API calls", "REST/HTTPS")
Rel_U(userUI, account, "Manage account", "REST/HTTPS")
Rel(userUI, ledger, "Transfer crypto internally", "REST/HTTPS")
Rel(userUI, deposit, "Request crypto deposit", "REST/HTTPS")
Rel(userUI, withdraw, "Request crypto withdraw", "REST/HTTPS")
Rel(auth, notification, "Notify Auth activity","Kafka Topic")
Rel(ledger, notification, "Notify transfer","Kafka Topic")
Rel(deposit, notification, "Notify deposit","Kafka Topic")
Rel(withdraw, notification, "Notify withdraw","Kafka Topic")
Rel_L(ledger, reconciliation, "Notify transfer","Kafka Topic")
Rel_U(deposit, reconciliation, "Notify deposit","Kafka Topic")
Rel_L(withdraw, reconciliation, "Notify withdraw","Kafka Topic")
Rel(notification, email, "Uses","REST/HTTPS")
Rel(email, user, "Send email to","SMTP")
Rel(system_boundary, r2, "All services do CRUD files from", "REST/HTTPS")

Rel(user, blockchain, "Transfer crypto to Ledger Hub wallet with id from deposit system","Crypto Wallet")
Rel(deposit, blockchain, "Verify deposit in","EVM")
Rel(withdraw, blockchain, "Transfer crypto to user in","EVM")

Rel_U(auditor, auditorUI, "Uses")
Rel(auditorUI, reconciliation, "Audit", "REST/HTTPS")
Rel(reconciliation, blockchain, "Read balance from", "EVM")

SHOW_LEGEND()
@enduml