/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    { type: "doc", id: "intro" },
    { type: "autogenerated", dirName: "tutorial-basics" },
    { type: "autogenerated", dirName: "tutorial-extras" },
  ],
  openApiSidebar: [
    {
      type: "category",
      label: "Bitka",
      link: {
        type: "generated-index",
        title: "Bitka API",
        description: "Bitka Exchange Public API Documentation",
        slug: "/openapi",
      },
      items: require("./docs/openapi/sidebar.js"),
    },
  ],
  developerGuideSidebar: [
    {
      type: "autogenerated",
      dirName: "developer-guide",
    },
  ],
};

export default sidebars;
